version: '2'
services:
  app:
    image: 'fintech-app:latest'
    build:
      context: .
    ports:
      - "8081:8080"
    container_name: fintechApp
    depends_on:
      - fintechDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fintechDb:5433/FinTechDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Orebela22
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  fintechDb:
    image: 'postgres:latest'
    container_name: fintechDb
    ports:
      - "5434:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Orebela22